version: '3.4'
services:
  confluence:
    image: haxqer/confluence:8.8.1
    container_name: confluence-srv
    environment:
       - TZ=Europe/Moscow
    #  - TZ=Asia/Shanghai
    #      - JVM_MINIMUM_MEMORY=1g
    #      - JVM_MAXIMUM_MEMORY=12g
    #      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    depends_on:
      - postgres
    ports:
      - "8090:8090"
    volumes:
      #- home_data:/var/confluence
      - e:/temp/confluence:/var/confluence
      #- /home/greglu/confluence/confluence:/var/confluence
    restart: always
    networks:
      - network-bridge

  postgres:
    image: postgres:14.3-alpine
    container_name: psql-confluence
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    ports:
    - "5432:5432"
    volumes:
      - e:/temp/psql_data:/var/lib/postgresql/data
    restart: always
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge

